version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword 
      MYSQL_DATABASE: trippie
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./migration:/docker-entrypoint-initdb.d

  nextjs:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=db
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db

volumes:
  mysql_data: